# Generated by Django 4.2 on 2023-04-17 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 0, 51, 56, 615407, tzinfo=datetime.timezone.utc)),
        ),
    ]
